{
 "title": "Node Detail",
 "tags": [ "nodes" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "aci", "label": "ACI", "query": { "query": "label_values(aci)" } },
   {
    "name": "podid",
    "label": "Podid",
    "query": {
     "query": "query_result(aci_health_ratio{class=\"fabricHealthTotal\", aci=\"$aci\"})"
    }
   },
   {
    "name": "nodeid",
    "label": "Nodeid",
    "query": {
     "query": "label_values(aci_health_ratio{aci=~\"$aci\",nodeid!~\"1\"}, nodeid) "
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Spine health (current)",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "aci_health_ratio{aci=~\"$aci\",podid=~\"$podid\",nodeid=~\"$nodeid\", role=\"spine\"}*100  ",
     "legendFormat": "Pod {{podid}} Node {{nodeid}}"
    }
   ]
  },
  {
   "title": "Leaf health (current)",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "aci_health_ratio{aci=~\"$aci\",podid=~\"$podid\",nodeid=~\"$nodeid\",role=\"leaf\"}*100  ",
     "legendFormat": "{{nodeid}}"
    }
   ]
  },
  {
   "title": "Node cpu",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "aci_node_cpu_user_ratio{aci=~\"$aci\",podid=~\"$podid\",nodeid=~\"$nodeid\"}*100  + aci_node_cpu_kernel_ratio{aci=~\"$aci\",podid=~\"$podid\",nodeid=~\"$nodeid\"}*100 ",
     "legendFormat": "{{nodeid}}"
    }
   ]
  },
  {
   "title": "Node memory used",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(aci_node_memory_used_bytes{aci=~\"$aci\",podid=~\"$podid\",nodeid=~\"$nodeid\"} / (aci_node_memory_used_bytes{aci=~\"$aci\",podid=~\"$podid\",nodeid=~\"$nodeid\"}  + aci_node_memory_free_bytes{aci=~\"$aci\",podid=~\"$podid\",nodeid=~\"$nodeid\"})) * 100",
     "legendFormat": "{{nodeid}}"
    }
   ]
  },
  {
   "title": "Fail operational mode",
   "type": "stat",
   "gridPos": { "h": 42, "w": 24, "x": 0, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aci_interface_oper_state{aci=~\"$aci\", podid=~\"$podid\",nodeid=~\"$nodeid\"} != 2\n",
     "legendFormat": "{{nodeid}}  {{interface}}"
    }
   ]
  },
  {
   "title": "Node health ",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 78 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "aci_health_ratio{aci=~\"$aci\",podid=~\"$podid\",nodeid=~\"$nodeid\"}*100  ",
     "legendFormat": "{{nodeid}} ({{role}})"
    }
   ]
  }
 ]
}