{
 "title": "Overview ACI",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "aci", "label": "ACI", "query": { "query": "label_values(aci)" } },
   {
    "name": "podid",
    "label": "Podid",
    "query": {
     "query": "query_result(aci_health_ratio{class=\"fabricHealthTotal\", aci=\"$aci\"})"
    }
   },
   {
    "name": "classes",
    "label": "Classes",
    "query": {
     "query": "label_values(aci_health_ratio{ }, class) "
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Fabric Health %",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "repeat": "Podid",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aci_health_ratio{aci=~\"$aci\",class=\"fabricHealthTotal\", podid=~\"$podid\"}*100  ",
     "legendFormat": " Podid {{podid}}"
    }
   ]
  },
  {
   "title": "APIC nodes",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "aci_infra_node_info{aci=~\"$aci\"}"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "aci_nodes{aci=~\"$aci\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Resource usage",
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aci_object_instances{aci=\"$aci\"}/aci_max_capacity{aci=\"$aci\"}",
     "legendFormat": "{{class}}"
    }
   ]
  },
  {
   "title": "Nodes <99%",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(aci_health_ratio{aci=~\"$aci\",podid=~\"$podid\",role=\"leaf\",class=\"topSystem\"} < 0.99)",
     "legendFormat": "leaf "
    },
    {
     "expr": "count(aci_node_health_ratio{aci=~\"$aci\",podid=~\"$podid\",role=\"spine\",class=\"topSystem\"} < 0.99)",
     "legendFormat": "spine"
    }
   ]
  },
  {
   "title": "Node id <99%",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "aci_health_ratio{aci=~\"$aci\",podid=~\"$podid\",role=\"leaf\",class=\"topSystem\"} * 100 < 99",
     "legendFormat": "{{nodeid}}"
    }
   ]
  },
  {
   "title": "Count objects",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": " count by (class) (aci_health_ratio{aci=~\"$aci\", class=~\"$classes\",role!=\"controller\"})",
     "legendFormat": "{{object}}"
    }
   ]
  },
  {
   "title": "Healt 95 -99%",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "  count by (class) (aci_health_ratio{aci=~\"$aci\", class=~\"$classes\",role!=\"controller\"}  >= 0.95) - count by (class) (aci_health_ratio{aci=~\"$aci\", class=~\"$classes\",role!=\"controller\"}  > 0.99)",
     "legendFormat": "{{object}}"
    }
   ]
  },
  {
   "title": "Healt 90 -95%",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "  count by (class) (aci_health_ratio{aci=~\"$aci\", class=~\"$classes\",role!=\"controller\"}  >= 0.90) - count by (class) (aci_health_ratio{aci=~\"$aci\", class=~\"$classes\",role!=\"controller\"}  > 0.95)",
     "legendFormat": "{{object}}"
    }
   ]
  },
  {
   "title": "Healt 0 -90%",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "  count by (class) (aci_health_ratio{aci=~\"$Aci\", class=~\"$Classes\",role!=\"controller\"}  >= 0.0) - count by (class) (aci_health_ratio{aci=~\"$Aci\", class=~\"$Classes\",role!=\"controller\"}  > 0.90)",
     "legendFormat": "{{object}}"
    }
   ]
  },
  {
   "title": "Tenants Health",
   "type": "table",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "aci_health_ratio{aci=~\"$aci\",class=~\"fvTenant\"} * 100"
    }
   ]
  },
  {
   "title": "Ap Health",
   "type": "table",
   "gridPos": { "h": 10, "w": 4, "x": 4, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "aci_health_ratio{aci=~\"$aci\",class=~\"fvAp\"} * 100"
    }
   ]
  },
  {
   "title": "AEPg Health",
   "type": "table",
   "gridPos": { "h": 10, "w": 7, "x": 8, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "aci_health_ratio{aci=~\"$aci\",class=~\"fvAEPg\"} * 100"
    }
   ]
  },
  {
   "title": "Ctx Health",
   "type": "table",
   "gridPos": { "h": 10, "w": 4, "x": 15, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "aci_health_ratio{aci=~\"$aci\",class=~\"fvCtx\"} * 100"
    }
   ]
  },
  {
   "title": "Bridge Domain Health",
   "type": "table",
   "gridPos": { "h": 10, "w": 5, "x": 19, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "aci_health_ratio{aci=~\"$aci\",class=~\"fvBD\"} * 100"
    }
   ]
  },
  {
   "title": "Fabric Health Podid $podid",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "aci_health_ratio{aci=~\"$aci\",podid=~\"$podid\",class=\"fabricHealthTotal\"}*100  ",
     "legendFormat": "Podid {{podid}}"
    }
   ]
  },
  {
   "title": "Scrape",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "aci_scrape_duration_seconds{aci=~\"$aci\"}"
    }
   ]
  },
  {
   "title": "Faults operational",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aci_faults{aci=~\"$Aci\",type=\"operational\",severity!=\"warn\"}",
     "legendFormat": "{{type}} {{severity}}"
    }
   ]
  }
 ]
}