{
 "title": "Capacity ACI",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "fabric", "label": "Fabric", "query": { "query": "label_values(fabric)" } },
   {
    "name": "nodeid",
    "label": "Nodeid",
    "query": {
     "query": "query_result(aci_fabric_node_info{fabric=~\"$fabric\"})"
    }
   },
   { "name": "top", "label": "Top", "query": "5,10,50,1000" }
  ]
 },
 "panels": [
  {
   "title": "VRFs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk($top,\n  aci_node_scale_ctx{fabric=~\"$fabric\",nodeid=~\"$nodeid\",class=\"l3Dom\"} / on(fabric,nodeid)\n  (\n    aci_node_vrf_capacity{fabric=~\"$fabric\",nodeid=~\"$nodeid\"} and ignoring(configured_profile)aci_node_active_scale_profile{fabric=~\"$fabric\",nodeid=~\"$nodeid\"}\n  )\n) > 0",
     "legendFormat": "{{fabric}} - {{nodeid}}"
    }
   ]
  },
  {
   "title": "BDs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk($top,\n  aci_node_scale_ctx{fabric=~\"$fabric\",nodeid=~\"$nodeid\",class=\"l2BD\"} / on(fabric,nodeid)\n  (\n    aci_node_bd_capacity{fabric=~\"$fabric\",nodeid=~\"$nodeid\"} and ignoring(configured_profile)aci_node_active_scale_profile{fabric=~\"$fabric\",nodeid=~\"$nodeid\"}\n  )\n) > 0",
     "legendFormat": "{{fabric}} - {{nodeid}}"
    }
   ]
  },
  {
   "title": "EPGs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk($top, aci_node_scale_ctx{fabric=~\"$fabric\",nodeid=~\"$nodeid\",class=\"fvEpP\"} / on(fabric,nodeid)\n  (\n    aci_node_epg_capacity{fabric=~\"$fabric\",nodeid=~\"$nodeid\"} and ignoring(configured_profile)aci_node_active_scale_profile{fabric=~\"$fabric\",nodeid=~\"$nodeid\"}\n  )\n> 0)",
     "legendFormat": "{{fabric}} - {{nodeid}}"
    }
   ]
  },
  {
   "title": "ESGs Selectors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk($top,\n  aci_node_scale_ctx{fabric=~\"$fabric\",nodeid=~\"$nodeid\",class=\"fvEPSelectorDef\"} / on(fabric,nodeid)\n  (\n    aci_node_esgIp_capacity{fabric=~\"$fabric\",nodeid=~\"$nodeid\"} and ignoring(configured_profile)aci_node_active_scale_profile{fabric=~\"$fabric\",nodeid=~\"$nodeid\"}\n  )\n)  > 0",
     "legendFormat": "IP Selectior {{fabric}} - {{nodeid}} "
    },
    {
     "expr": "topk($top,\n  aci_node_scale_ctx{fabric=~\"$fabric\",nodeid=~\"$nodeid\",class=\"fvMacBdSelectorDef\"} / on(fabric,nodeid)\n  (\n    aci_node_max_esgMac{fabric=~\"$fabric\",nodeid=~\"$nodeid\"} and ignoring(configured_profile)aci_node_active_scale_profile{fabric=~\"$fabric\",nodeid=~\"$nodeid\"}\n  )\n) != 0",
     "legendFormat": "Mac Selectior {{fabric}} - {{nodeid}} "
    }
   ]
  },
  {
   "title": "MAC",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk($top,\n  aci_node_mac_current{fabric=~\"$fabric\",nodeid=~\"$nodeid\"} / aci_node_mac_capacity{fabric=~\"$fabric\",nodeid=~\"$nodeid\"} \n) > 0",
     "legendFormat": "{{fabric}} - {{nodeid}}"
    }
   ]
  },
  {
   "title": "IPv4",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk($top,\n  aci_node_ipv4_current{fabric=~\"$fabric\",nodeid=~\"$nodeid\"} / on(fabric,nodeid)\n  (\n    aci_node_ipv4_capacity{fabric=~\"$fabric\",nodeid=~\"$nodeid\"} and ignoring(configured_profile)aci_node_active_scale_profile{fabric=~\"$fabric\",nodeid=~\"$nodeid\"}\n  )\n) > 0",
     "legendFormat": "{{fabric}} - {{nodeid}}"
    }
   ]
  },
  {
   "title": "IPv6",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk($top,\n  aci_node_ipv6_current{fabric=~\"$fabric\",nodeid=~\"$nodeid\"} / on(fabric,nodeid)\n  (\n    aci_node_ipv6_capacity{fabric=~\"$fabric\",nodeid=~\"$nodeid\"} and ignoring(configured_profile)aci_node_active_scale_profile{fabric=~\"$fabric\",nodeid=~\"$nodeid\"}\n  )\n) > 0",
     "legendFormat": "{{fabric}} - {{nodeid}}"
    }
   ]
  },
  {
   "title": "MCAST Routes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk($top,\n  (aci_node_mcast_cum{fabric=~\"$fabric\",nodeid=~\"$nodeid\"} - aci_node_mcast_base{fabric=~\"$fabric\",nodeid=~\"$nodeid\"})\n   /\n   (aci_node_mcast_capacity_cum{fabric=~\"$fabric\",nodeid=~\"$nodeid\"} - aci_node_mcast_capacity_base{fabric=~\"$fabric\",nodeid=~\"$nodeid\"})\n) > 0",
     "legendFormat": "{{fabric}} - {{nodeid}}"
    }
   ]
  },
  {
   "title": "VLANs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk($top,\n  (aci_node_vlan_cum{fabric=~\"$fabric\",nodeid=~\"$nodeid\"} - aci_node_vlan_base{fabric=~\"$fabric\",nodeid=~\"$nodeid\"})\n  /\n  (aci_node_vlan_capacity_cum{fabric=~\"$fabric\",nodeid=~\"$nodeid\"} - aci_node_vlan_capacity_base{fabric=~\"$fabric\",nodeid=~\"$nodeid\"})\n) > 0",
     "legendFormat": "{{fabric}} - {{nodeid}}"
    }
   ]
  },
  {
   "title": "TCAM",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk($top,\n  (aci_node_policy_cum{fabric=~\"$fabric\",nodeid=~\"$nodeid\"} - aci_node_policy_base{fabric=~\"$fabric\",nodeid=~\"$nodeid\"})\n  /\n  (aci_node_policy_capacity_cum{fabric=~\"$fabric\",nodeid=~\"$nodeid\"} - aci_node_policy_capacity_base{fabric=~\"$fabric\",nodeid=~\"$nodeid\"})\n) > 0",
     "legendFormat": "{{fabric}} - {{nodeid}}"
    }
   ]
  },
  {
   "title": "LPM",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk($top,\n  aci_node_lpm_current{fabric=~\"$fabric\",nodeid=~\"$nodeid\"} / on(fabric,nodeid)\n  ( \n    aci_node_lpm_capacity{fabric=~\"$fabric\",nodeid=~\"$nodeid\"} and ignoring(configured_profile)aci_node_active_scale_profile{fabric=~\"$fabric\",nodeid=~\"$nodeid\"}\n  )\n) > 0",
     "legendFormat": "{{fabric}} - {{nodeid}}"
    }
   ]
  },
  {
   "title": "/32 Routes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk($top,\n  (aci_node_slash32_cum{fabric=~\"$fabric\",nodeid=~\"$nodeid\"} - aci_node_slash32_base{fabric=~\"$fabric\",nodeid=~\"$nodeid\"})\n  / on(fabric,nodeid)\n  (\n    aci_node_slash32_capacity{fabric=~\"$fabric\",nodeid=~\"$nodeid\"} and ignoring(configured_profile)aci_node_active_scale_profile{fabric=~\"$fabric\",nodeid=~\"$nodeid\"}\n  )\n) > 0",
     "legendFormat": "{{fabric}} - {{nodeid}}"
    }
   ]
  },
  {
   "title": "Labels",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk($top,\n  (aci_node_labels_cum{fabric=~\"$fabric\",nodeid=~\"$nodeid\"} - aci_node_labels_base{fabric=~\"$fabric\",nodeid=~\"$nodeid\"})\n   /\n   (aci_node_labels_capacity_cum{fabric=~\"$fabric\",nodeid=~\"$nodeid\"} - aci_node_labels_capacity_base{fabric=~\"$fabric\",nodeid=~\"$nodeid\"})\n) > 0",
     "legendFormat": "{{fabric}} - {{nodeid}}"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aci_fabric_node_info{role=\"controller\",fabric=~\"$fabric\"})",
     "legendFormat": "controller"
    },
    {
     "expr": "sum(aci_fabric_node_info{role=\"leaf\",fabric=~\"$fabric\"})",
     "legendFormat": "Leaf"
    },
    {
     "expr": "sum(aci_fabric_node_info{role=\"spine\",fabric=~\"$fabric\"})",
     "legendFormat": "Spine"
    }
   ]
  },
  {
   "title": "/128 Routes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk($top,\n  ( aci_node_slash128_current{fabric=~\"$fabric\",nodeid=~\"$nodeid\"} - aci_node_slash128_base{fabric=~\"$fabric\",nodeid=~\"$nodeid\"}) / on(fabric,nodeid) \n  ( \n    aci_node_slash128_capacity{fabric=~\"$fabric\",nodeid=~\"$nodeid\"} and ignoring(configured_profile)aci_node_active_scale_profile{fabric=~\"$fabric\",nodeid=~\"$nodeid\"}\n  )\n) > 0",
     "legendFormat": "{{fabric}} - {{nodeid}}"
    }
   ]
  }
 ]
}