{
 "title": "Routing Protocols",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "fabric", "label": "Fabric", "query": { "query": "label_values(fabric)" } },
   {
    "name": "nodeid",
    "label": "Nodeid",
    "query": {
     "query": "query_result(aci_fabric_node_info{fabric=~\"$fabric\",role!=\"controller\"})"
    }
   },
   {
    "name": "vrf",
    "label": "Vrf",
    "query": {
     "query": "query_result(aci_bgp_peer_prefix_received{fabric=~\"$fabric\"} or aci_ospf_neighbors{fabric=~\"$fabric\"})"
    }
   },
   { "name": "top", "label": "Top", "query": "5,10,50,100,1000" }
  ]
 },
 "panels": [
  {
   "title": "L3 Neighbours",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "topk($top,(time() - (aci_ospf_neighbors{fabric=~\"$fabric\",nodeid=~\"$nodeid\",vrf=~\"$vrf\"} or aci_bgp_peers{fabric=~\"$fabric\",nodeid=~\"$nodeid\",vrf=~\"$vrf\"})))",
     "legendFormat": "{{fabric}} - {{nodeid}}"
    }
   ]
  },
  {
   "title": "BGP Advertised Paths",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "topk($top,aci_bgp_peer_prefix_sent{fabric=~\"$fabric\",nodeid=~\"$nodeid\",vrf=~\"$vrf\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "BGP Accepted Paths",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "topk($top,aci_bgp_peer_prefix_received{fabric=~\"$fabric\",nodeid=~\"$nodeid\",vrf=~\"$vrf\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "BGP Accepted Paths",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "topk($top,aci_bgp_peer_prefix_received{fabric=~\"$fabric\",nodeid=~\"$nodeid\",vrf=~\"$vrf\"})",
     "legendFormat": "{{fabric}} - {{nodeid}} - {{vrf}}"
    }
   ]
  }
 ]
}